const REFRESH_TIME = 1000 * 10;
const REFRESH_BALANCE = 3;
const INITIAL_DATE = new Date();
const INITIAL_BALANCE = 5;

module.exports = {
  REFRESH_BALANCE,
  REFRESH_TIME,
  INITIAL_DATE,
  INITIAL_BALANCE,
};
